name: Testing

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: test_redirector
      run: cd redirector; cargo test --verbose
    - name: test_rules
      run: cd ../rulelib; cargo test --verbose

